all	: echod

clean	: echod-clean

clean-all	: echod-clean-all

.PHONY	: echod echod-clean echod-clean-all
echod	:
	cd echod && $(MAKE)
echod-clean	:
	cd echod && $(MAKE) clean
echod-clean-all	:
	cd echod && $(MAKE) clean-all
